FROM ubuntu:latest

RUN apt-get update && apt-get install -y samba

COPY smb.conf /etc/samba/smb.conf

RUN useradd -m -s /bin/bash sambauser && echo -e "password\npassword" | smbpasswd -a -s sambauser

EXPOSE 137 138 139 445

CMD ["smbd", "--foreground", "--no-process-group"]

