FROM osixia/openldap:1.5.0

ENV LDAP_ORGANISATION="Example Inc."
ENV LDAP_DOMAIN="example.org"
ENV LDAP_ADMIN_PASSWORD="admin"

COPY ldap-config.ldif /container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

EXPOSE 389 636

