name: Build Container

on:
  push:
    branches:
    - master
    tags:
    - "**"

permissions:
  packages: write
  contents: write

jobs:
  build_docker:
    name: build docker
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run build script
        run: ./build_containers.sh

